#!/bin/bash

# Reboot Now!
# Based on the infamous 'shutdown script' 
# authored on Dec-31-2022
# by b4t54ndw1ch

# Version 1
# Notes: RebootNow! is designed to be a single file that 
# resides on the desktop.  It is designed to look like a button
# and reboot the computer down with one click, thereby achieving
# the fastest possible safe system reboot. 

# (*This is a statement of intention, not a legal claim)

echo 'Rebooting now.  See you again soon!'

reboot

# Todo: add date and time display to output message
# Todo: change icon to look like a button
